// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHw1EvKxGms5JpxlWXfQXSVmo34ILvSWY',
    appId: '1:1099115273236:web:fbceab7e1fe2a4a6475b01',
    messagingSenderId: '1099115273236',
    projectId: 'coiffeasy-4adf1',
    authDomain: 'coiffeasy-4adf1.firebaseapp.com',
    storageBucket: 'coiffeasy-4adf1.firebasestorage.app',
    measurementId: 'G-WQ8RE5J6RZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK7BsUzVT4EQmgdYgDEasrWBaDAWK9JFU',
    appId: '1:1099115273236:android:994edf6b822fbed5475b01',
    messagingSenderId: '1099115273236',
    projectId: 'coiffeasy-4adf1',
    storageBucket: 'coiffeasy-4adf1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrXc_mhWAGdg6B7ZVVEcu126VORClCfWk',
    appId: '1:1099115273236:ios:8c99a5a1684bfc23475b01',
    messagingSenderId: '1099115273236',
    projectId: 'coiffeasy-4adf1',
    storageBucket: 'coiffeasy-4adf1.firebasestorage.app',
    iosBundleId: 'com.example.gestionJr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrXc_mhWAGdg6B7ZVVEcu126VORClCfWk',
    appId: '1:1099115273236:ios:8c99a5a1684bfc23475b01',
    messagingSenderId: '1099115273236',
    projectId: 'coiffeasy-4adf1',
    storageBucket: 'coiffeasy-4adf1.firebasestorage.app',
    iosBundleId: 'com.example.gestionJr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHw1EvKxGms5JpxlWXfQXSVmo34ILvSWY',
    appId: '1:1099115273236:web:6f036ceba92bd160475b01',
    messagingSenderId: '1099115273236',
    projectId: 'coiffeasy-4adf1',
    authDomain: 'coiffeasy-4adf1.firebaseapp.com',
    storageBucket: 'coiffeasy-4adf1.firebasestorage.app',
    measurementId: 'G-NRC6Q7BDGB',
  );
}
